### ISSUE TITLE
How to listen to Asterisk Manager Proxy 

### ISSUE THREAD

**Issue by muneeb249** [skrusty/AsterNET#20]
I have developed a C# application listening to AMI Events (Thanks to Aster.NET Api). But I found out that AMI looses connection to Asterisk when there are a lot of calls coming and going. One solution is to add a Asterisk Manager Proxy between AMI and Asterisk, is there any away in Aster.NET api to provide Asterisk Manager Proxy implementations.
Thanks in advance

**Comment by jonasswiatek** [comment]
What exactly do you mean with a proxy in this case?

Most likely you're losing connection either because you're getting an exception in one of your event handlers, or you need to increase the write timeout for the AMI connection in Asterisk.

**Comment by skrusty** [comment]
I agree with @jonasswiatek more often than not, the manager connection gets reset because of an unhandled exception. It's something we need to better handle long term when events are fired in AsterNET. By default an exception (if i remember right) assumes we need to close the socket!

There are AMI proxies out there, but I doubt this is really the issue you're having.

**Comment by muneeb249** [comment]
Actually I want to use AMI proxies in my code.
And yes @jonasswiatek  I want to increase the Write time of the AMI connection to Asterisk

**Comment by skrusty** [comment]
You can use AsterNET to create a proxy. You could also use AsterNET (I think) as the API for your proxy client I guess. I would maybe have a look at existing proxies, see how they differ from standard AMI and what changes you may need to make to AsterNET.
