### ISSUE TITLE
Core Show Cahnnel Command

### ISSUE THREAD

**Issue by k07** [skrusty/AsterNET#55]
Action: CoreShowChannels
ActionID: 100
This is my Code Section
-----
AsterNET.Manager.Action.CoreShowChannelsAction coreSC = new Manager.Action.CoreShowChannelsAction();
coreSC.ActionId = "100";
AsterNET.Manager.Response.ManagerResponse response = manager.SendAction(coreSC);

*Is it Correct way to send AMI command for CoreShowChannel Action*

**Comment by k07** [comment]
What type of issues Can I post in this site ???i am new in  asterisk and asternet  I facing lot of issues  but i didn't get any solution for my issues  from this site..

**Comment by skrusty** [comment]
Firstly, please stop posting issues with the same topic or for the same issue more than once. We are a community of volunteers. We are not paid support.

With regards to sending an AMI Action, as mentioned in previous posts to you on this site, the best reference we have that is a working example is the Test application.

As you can see in the test application, you don't need to set the Action ID yourself, you can simply allow AsterNET to add that for you.

However, because you're not aware of how AMI works, the approach you've taken to this won't work. Again, if you need help understanding how to work with Asterisk and AMI, I would point you directly to the existing Asterisk Forums.

If you are trying to get a list of active calls, and keep and maintain that list, using 'CoreShowChannelsAction' is only part of the solution. You want to look for an event that informs you about the channels (new and existing) in Asterisk.

## Getting initial channel list
There are two ways to do this.

**Method 1 (Not the best way!):**
Send the action 'CoreShowChannelsAction' to get an initial list of channels. (You'll need to listen for CoreShowChannelsCompleteEvent events in response, see below for more about this).

If you had read the documentation for Asterisk AMI, you would have seen this:
https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerEvent_CoreShowChannel

TO send the initial 'CoreShowChannelsAction' action, simply do:

```c#
var response = manager.SendAction(new CoreShowChannelsAction());
```

However, this itself doesn't return a result, but tells Asterisk to send 'CoreShowChannels' events to AsterNET. You need to monitor this event, HOWEVER, as yet there is no event mapping directly setup in AsterNET to handle this. As a result you'll need to use UnhandledEvent to listen for these responses.

```c#
manager.UnhandledEvent += new ManagerEventHandler(mc_UnhandledEvent);

private void mc_UnhandledEvent(object sender, Asterisk.NET.Manager.Event.ManagerEvent e)
        {
            switch (e.Attributes["name"])
            {
                case "CoreShowChannelsComplete":
                    // your code here once list is finished
                    break;
                case "CoreShowChannels":
                    // your code here to handle each channel
                    break;
            }
        }
```

**Method 2 (A better way):**
Use the Status action and Status events. These are better handled in AsterNET!

```c#
manager.StatusComplete += new StatusCompleteEventHandler(Current_StatusComplete);
manager.Status += new StatusEventHandler(Current_Status);
```

Then put your code on those event handlers

```c#
private void Current_Status(object sender, Asterisk.NET.Manager.Event.StatusEvent e)
{
    // your code here to handle the channel that's active in Asterisk
}

private void Current_StatusComplete(object sender, Asterisk.NET.Manager.Event.StatusCompleteEvent e)
{
    // any code here you want to run once the list of channels is complete
}
```

## Maintaining that channel list
The event that will inform you about new channels is: NewChannel.

Use these in combination to ensure a) you have an initial list of channels and b) to ensure you can model the state of those and new channels.

You will of course want to ensure you track the channels to see when they are destroyed also. This can be done with the 'NewState' event. This will help you understand what's happening to those channels.

**Comment by nirzaf** [comment]
Hi Can Someone show me an example how to implement this, I am getting the Permission Denied Message while sending CoreShowChannels Action, Please Help
